-- Retired: the user requested the 34 original BOM materials instead.
-- Run populate_bom_34_stock.sql to remove the old samples and initialize stock.
-- This file intentionally makes no database changes.
