// Referring-agent values from upload2.csv and supabase_admin_ready.csv.
// Preserve compound names and source spellings; do not infer separate people.
export const COLLECTED_REFERRING_AGENTS = [
    "AKSHAY",
    "ASHISH",
    "ASHUTOSH",
    "AVP",
    "DARIYA",
    "DEEP",
    "DEEP/NIRAV",
    "DHARMESH",
    "DIGPALSINH",
    "GALAXY SOLAR",
    "GANDHIDHAM",
    "HARISH",
    "JP SONS / JAYDEEP",
    "KANO",
    "KUTUB",
    "MAHIPAT",
    "PARAS",
    "PARESH",
    "PARESHBHAI INSTALLER",
    "RAGHUVEER",
    "RAJ",
    "RAJNI",
    "RAJNI BHADARIYA",
    "SANJIV",
    "SAYONAAM",
    "SFIYN",
    "SHIV",
    "SHIV (RAJKOT)",
    "SHIV ENTERPRISE",
    "SHUBHAM",
    "SHYAMBHAI",
    "SUFIYAN",
    "SUNRISE",
    "VIMAL",
    "VIPUL",
    "YASH",
    "YASH/ DEEP",
    "YASH/ VIMAL",
    "YASH/DEEP",
    "YATIN"
];
